workspace:
  base: /vue
  path: src/github.com/readr-media/readme
pipeline:
  start_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}* <${DRONE_BUILD_LINK}|#{{build.number}}>.
      Someone gave *{{build.branch}}* a little push.
    when:
      event: [push]
      branch: [dev, master]

  get_dev_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone default default
    - cp default/readme/config.js api/
    - cp default/readr-site/gcskeyfile.json ./gcskeyfile.json
    when:
      event: [push]
      branch: [dev]

  get_master_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone default default
    - cp default/k8s-deploy/readr-prod/readme/config.js api/
    - cp default/readr-site/gcskeyfile.json ./gcskeyfile.json
    when:
      event: [push]
      branch: [master]

  builds:
    image: node:10-alpine  # alpine=3.9
    pull: true
    commands:
    - apk update
    - apk add vips vips-dev fftw build-base python musl --update-cache --repository https://alpine.global.ssl.fastly.net/alpine/edge/community/ --repository https://alpine.global.ssl.fastly.net/alpine/edge/main/
    - yarn install
    - yarn run build
    when:
      event: [push]
      branch: [dev, master]

  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [google_credentials]
    when:
      event: [push]
      branch: [dev, master]

  deploy_dev:
    image: nytimes/drone-gke
    zone: asia-east1-a
    cluster: dev
    namespace: default
    # For debugging
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
      app: ${DRONE_REPO_NAME}
      tier: frontend
    when:
      event: [push]
      branch: [dev]

  deploy_master:
    image: nytimes/drone-gke
    zone: asia-east1-a
    cluster: prod-readr
    namespace: default
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
      app: ${DRONE_REPO_NAME}
      tier: frontend
    when:
      event: [push]
      branch: [master]

  finish_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
      branch: [dev, master]
    template: >
      {{#success build.status}}
        *success* ${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <http://cms-dev.readr.tw|readme>.
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed.
      {{/success}}
