export const apiMap = [
  { item: 'project', target: 'project/update', method: 'PUT', },
  { item: 'report', target: 'report/update', method: 'PUT' },
  { item: 'memo', target: 'memo/update', method: 'PUT' },
  { item: 'member', target: 'member/update', method: 'PUT' },
  { item: 'project', target: 'project', method: 'DELETE', },
  { item: 'report', target: 'report', method: 'DELETE' },
  { item: 'memo', target: 'memo', method: 'DELETE' },
  { item: 'member', target: 'member', method: 'DELETE' },
  { item: 'project', target: 'project', method: 'GET', },
  { item: 'report', target: 'report', method: 'GET' },
  { item: 'memo', target: 'memo', method: 'GET' },
  { item: 'member', target: 'member', method: 'GET' },
  { item: 'project', target: 'project/create', method: 'POST', },
  { item: 'report', target: 'report/create', method: 'POST' },
  { item: 'memo', target: 'memo/create', method: 'POST' },
  { item: 'member', target: 'member/create', method: 'POST' },
]